### PR TITLE
Fix pytvmaze

### PR DESCRIPTION
**Pull request by labrys**

### CODE REVIEW

**Comment by labrys** [comment]
@srob650 do you have a premium account for testing tvmaze?

**Comment by srob650** [comment]
Yes

**Comment by srob650** [comment]
FYI:

```
>>> from pytvmaze.tvmaze.premium import TVMazePremium as TVMaze
>>> tvm = TVMaze('srob650', '123456')
>>> tvm.follow_network(9)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze/premium.py", line 52, in follow_network
    q = self._endpoint_premium_put(url)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze/premium.py", line 43, in _endpoint_premium_put
    response = cls.authorized_request(url=url, *args, **kwargs)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze/premium.py", line 19, in authorized_request
    if not cls.session.auth:
AttributeError: 'NoneType' object has no attribute 'auth'
```

Obviously I had my real api_key in there when testing.

**Comment by labrys** [comment]
@srob650 It should be fixed in my current version, but it'll be a while till i get to push the latest changes. If you want to test in the meantime:

In TVMazePremium.authorized_request change:
```python
    @classmethod
    def authorized_request(cls, *args, **kwargs):
        if not cls.session.auth:
```
to
```python
    @classmethod
    def authorized_request(cls, *args, **kwargs):
        if not cls.session:
            cls.session = cls.make_session()
        if not cls.session.auth:
```

I'm going to be improving the session handler in the future.  And then this will change, but this should work for now.

**Comment by srob650** [comment]
@labrys No worries, I'll try testing again after the next push or two just to confirm premium features

**Comment by labrys** [comment]
I'll push a previous commit, because right now im looking at some major refactoring to remove circular dependencies, so it might take a while.

**Comment by srob650** [comment]
There's really no rush, but if you want to go for it and I'll test

**Comment by labrys** [comment]
Well I'd like to make sure those features are working, that's more important than the refactoring.  It should be testable as is now.

**Comment by srob650** [comment]
Cool

**Comment by srob650** [comment]
@labrys 
> In TVMazePremium.authorized_request change:

> 
>     @classmethod
>     def authorized_request(cls, *args, **kwargs):
>         if not cls.session.auth:
> to
> 
>     @classmethod
>     def authorized_request(cls, *args, **kwargs):
>         if not cls.session:
>             cls.session = cls.make_session()
>         if not cls.session.auth:

Tried this and got a new error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze/premium.py", line 54, in follow_network
    q = self._endpoint_premium_put(url)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze/premium.py", line 45, in _endpoint_premium_put
    response = cls.authorized_request(url=url, *args, **kwargs)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze/premium.py", line 26, in authorized_request
    raise exceptions.NotAuthorized
TypeError: __init__() missing 1 required positional argument: 'value'
```

**Pull request closed without merging**
